sylius_grid:
    grids:
        jchr86_sylius_banner_admin_banner:
            driver:
                options:
                    class: Jchr86\SyliusBannerPlugin\Entity\Banner
            sorting:
                code: asc
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: ~
            filters:
                code:
                    type: string
                    label: sylius.ui.code
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
