services:
    jchr86_sylius_banner.listener.admin.menu_builder:
        class: Jchr86\SyliusBannerPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    jchr86_sylius_banner.form.type.banner:
        class: Jchr86\SyliusBannerPlugin\Form\Type\BannerType
        arguments: [Jchr86\SyliusBannerPlugin\Entity\Banner]
        tags:
            - { name: form.type }

    jchr86_sylius_banner.form.type.banner_image:
        class: Jchr86\SyliusBannerPlugin\Form\Type\BannerImageType
        arguments: [Jchr86\SyliusBannerPlugin\Entity\BannerImage]
        tags:
            - { name: form.type }

    jchr86_sylius_banner.listener.images_upload:
        class: Sylius\Bundle\CoreBundle\EventListener\ImagesUploadListener
        autowire: true
        tags:
            - { name: kernel.event_listener, event: jchr86_sylius_banner.banner.pre_create, method: uploadImages }
            - { name: kernel.event_listener, event: jchr86_sylius_banner.banner.pre_update, method: uploadImages }
